version: 2

jobs:
  build:
    environment:
      CLOUDSDK_CORE_PROJECT: "test-project"
      GOOGLE_APPLICATION_CREDENTIALS: "service_account.json"
    docker:
      - image: echomobi/echomobile-ci:v1.2
    working_directory: ~/datastore-entities
    steps:
      - run:
          name: Start Datastore Emulator
          command: gcloud beta emulators datastore start
          background: true

      - checkout

      # adds a dummy service key to allow creation of a client for testing
      - run:
          name: Add Service Account
          command: echo $FAKE_SERVICE_ACCOUNT>service_account.json

      - restore_cache:
          name: Restore python cache
          keys:
            - requirements-{{ checksum "requirements.txt" }}

      - run:
          name: Create venv and install requirements
          command: |
            if [ -e ./venv ]; then
              echo "Using cached venv"
            else
              echo "Creating venv"
              python3.7 -m venv venv
              echo "Install requirements"
              . venv/bin/activate && pip install -r requirements.txt && deactivate
            fi

      - save_cache:
          name: Save python cache
          key: requirements-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          command: |
            $(gcloud beta emulators datastore env-init)
            . venv/bin/activate
            coverage run tests/run.py
            codecov
          name: Run Tests
